"""empty message

Revision ID: 52ee00826f47
Revises: 757ec5543d22
Create Date: 2020-12-19 14:15:42.948260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52ee00826f47'
down_revision = '757ec5543d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('audience_id', table_name='reservations')
    op.drop_index('id', table_name='reservations')
    op.drop_index('user_id', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('id', table_name='users')
    op.drop_table('users')
    op.drop_index('id', table_name='audiences')
    op.drop_index('user_id', table_name='audiences')
    op.drop_table('audiences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiences',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price_for_hour', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audiences_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'audiences', ['user_id'], unique=True)
    op.create_index('id', 'audiences', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('second_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('birthday', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=345), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'users', ['id'], unique=True)
    op.create_table('reservations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('start_time', mysql.TIMESTAMP(), nullable=False),
    sa.Column('end_time', mysql.TIMESTAMP(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('audience_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['audiences.id'], name='reservations_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reservations_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'reservations', ['user_id'], unique=True)
    op.create_index('id', 'reservations', ['id'], unique=True)
    op.create_index('audience_id', 'reservations', ['audience_id'], unique=True)
    # ### end Alembic commands ###
