"""empty message

Revision ID: 757ec5543d22
Revises: 
Create Date: 2020-11-29 21:09:01.812828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757ec5543d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('second_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('birthday', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=345), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('audiences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('price_for_hour', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('audience_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['audiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('audiences')
    op.drop_table('users')
    # ### end Alembic commands ###
